apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniorest
  labels:
    app: miniorest
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"miniorest:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"miniorest-container\")].image"}]
spec:
  selector:
    matchLabels:
      app: miniorest
  template:
    metadata:
      labels:
        app: miniorest
    spec:
      containers:
      - name: miniorest-container
        image: image-registry.openshift-image-registry.svc:5000/miniorest/miniorest:latest
        ports:
        - containerPort: 9080
        envFrom:
          - secretRef:
              name: cos-secret            